
name: OPA Policy Check - SEC-002

on:
  push:
    paths:
      - 'policies/security/SEC-002-no-permit-all.rego'
      - 'controls/SEC-002/input/spring_security.json'
      - 'controls/SEC-002/SEC-002-control.yaml'
      - 'controls/SEC-002/.github/workflows/opa-sec-002.yml'
  pull_request:
    paths:
      - 'policies/security/SEC-002-no-permit-all.rego'
      - 'controls/SEC-002/input/spring_security.json'

jobs:
  opa-policy-check:
    runs-on: ubuntu-latest
    name: OPA Evaluation for SEC-002
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up OPA CLI
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Run SEC-002 Policy Evaluation
        run: |
          opa eval -d policies/security/SEC-002-no-permit-all.rego \
                   -i controls/SEC-002/input/spring_security.json \
                   "data.policies.security.violation" --format=json > opa_output.json
          cat opa_output.json

      - name: Fail if violations found
        run: |
          if jq -e '.result[0].expressions[0].value | length > 0' opa_output.json; then
            echo "❌ Violations found in SEC-002"
            exit 1
          else
            echo "✅ No violations found in SEC-002"
          fi
