name: Validate IaC vs Controls

on:
  pull_request:
    types:
      - opened
    branches:
      - main
    paths:
     - aac-direct-debit-update/infrastructure/**
  workflow_dispatch:

jobs:
  Validate-terraform-Control:
    name: ✅ IaC-Controls Compliance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Make script executable
        run: chmod +x scripts/validate_IaC_controls.py

      - name: Run validation script
        run: python ./scripts/validate_IaC_controls.py

      - name: Debug – List report files
        run: ls -l aac-direct-debit-update/compliance-reports || echo "Directory not found"

      - name: Upload report artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Iac-control-analysis-report
          path: aac-direct-debit-update/compliance-reports/IaC_control_analysis.md
