name: Validate Policy-Architecture Compliance

on:
  push:
    paths:
      - 'aac-direct-debit-update/architecture/DirectDebitMandateUpdateArchitectureComponentDiagram.puml'
  pull_request:
    paths:
      - 'aac-direct-debit-update/architecture/**/*.puml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r aac-direct-debit-update/requirements.txt || true

      - name: Make script executable
        run: chmod +x aac-direct-debit-update/scripts/validate_policy_architecture_compliance.py

      - name: Run validation script
        run: ./aac-direct-debit-update/scripts/validate_policy_architecture_compliance.py
