name: Validate Policy-Architecture Compliance

on:
  push:
    paths:
      - 'architecture/DirectDebitMandateUpdateArchitectureComponentDiagram.puml'
  pull_request:
    paths:
      - 'architecture/**/*.puml'
  workflow_dispatch:

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Make script executable
        run: chmod +x scripts/validate_policy_architecture_compliance.py

      - name: Run validation script
        run: python ./scripts/validate_policy_architecture_compliance.py
      
      - name: Upload report artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: policy-evaluation-report
          path: aac-direct-debit-update/aac-direct-debit-update_*/
